name: Welcome new contributors
on:
  pull_request_target:
    types: [opened]

jobs:
 greet:
   runs-on: ubuntu-latest
   steps: 
    - name: Greet the contributor
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: |
        Welcome! Thank you for your pull request.
        We appreciate your contribution.
